name: Build webOS IPK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install webOS CLI
        run: npm install -g @webosose/ares-cli
      - name: Package App
        run: ares-package .
      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: Funkora-TV-App
          path: ./*.ipk
- name: Package App
        run: |
          chmod +x -R .
          ares-package .
